### ISSUE TITLE
[REQUEST]: App ID & Secret

### ISSUE THREAD

**Issue by vivekkotadiya** [soketi/pws#1021]
@rennokki I couldn't locate any documentation on generating app ID and secret keys, or information on how to purchase a plan and where to do so. I kindly request guidelines on purchasing Soketi plans and registering for app ID and secret keys. It is mentioned that users can use Soketi's app ID and secret keys instead of Pusher's, but I haven't found any instructions on where to obtain Soketi's app ID and secret keys.

**Comment by adityaa-codes** [comment]
Soketi is an open source web server, you can deploy the soketi  on your own server, and generate app id and secret keys, anyway you like, you can check out app management https://docs.soketi.app/app-management/introduction
soketi is free, but the cost you'll be bearing is the server cost!

**Comment by vivekkotadiya** [comment]
@adityaa-codes Thanks for the information. Based on your answer what I understand is I can use any string for app id and app secret.

**Comment by adityaa-codes** [comment]
Yes, its just app id should be unique.
