### ISSUE TITLE
soketi can not working in Docker  ? 

### ISSUE THREAD

**Issue by bostin** [soketi/pws#1081]
My Image (running in k3s):
`quay.io/soketi/soketi:1.6-16-debian`

When i set SOKETI_DEBUG=1, the output is:
<img width="1070" alt="image" src="https://github.com/soketi/soketi/assets/17870778/65b7ef7a-84ed-4604-acc6-167aa52f9ead">

my config.json:
<img width="469" alt="image" src="https://github.com/soketi/soketi/assets/17870778/510509be-1311-4f82-b644-cb59af85c740">

According to `options.ts`, the `port` should be a number:
<img width="785" alt="image" src="https://github.com/soketi/soketi/assets/17870778/015743b6-8a1e-4a99-af3a-fdb9a64d4da7">

so, is server listening a wrong/invalid port ?:
<img width="1454" alt="image" src="https://github.com/soketi/soketi/assets/17870778/35b64371-d592-4634-8f3d-4993b1ddec8d">

**Comment by futurfuturfuturfutur** [comment]
Same here, getting this behaviour on k8s + traefik setup on production environment, however, it behaves properly using docker compose on development environment.

**Comment by futurfuturfuturfutur** [comment]
What is your docker setup? I have troubles only with k8s + traefik setup, docker and docker compose setup works properly, checked all versions, all of them listening wrong port on k8s + traefik, all of them listening valid 6001 port on docker

**Comment by futurfuturfuturfutur** [comment]
<img width="328" alt="Screenshot 2023-12-20 at 20 06 41" src="https://github.com/soketi/soketi/assets/81389337/36122daf-0148-41b1-af86-11842165a895">
Override port through SOKETI_PORT env solved the problem for me

**Comment by bostin** [comment]
@futurfuturfuturfutur Thanks, `SOKETI_PORT=6001` solved!

<img width="668" alt="image" src="https://github.com/soketi/soketi/assets/17870778/4db3b4be-3c86-453d-abe3-2cb68752f643">
