### ISSUE TITLE
[BUG] dash.soketi.app is down (522)

### ISSUE THREAD

**Issue by SnakeO** [soketi/pws#1120]
https://dash.soketi.app/register shows a 522 timeout.

![](https://wow-ss-from-2020.s3.amazonaws.com/Screen-Shot-2024-03-02-14-38-06.48.png)

**Comment by Tiagospem** [comment]
up

**Comment by Tiagospem** [comment]
@rennokki Will this be resolved? My company uses this service, I would not like to look for an alternative solution again :/

**Comment by paulocastellano** [comment]
Two weeks offline it's insane... let's move to reverb.

**Comment by Tiagospem** [comment]
@paulocastellano já comecei a implementar o reverb, muito fácil, só criar uma instalação limpa do laravel 11, subir lá pro forge que o restante é tudo automático. Agora com essa versão vai ser difícil o soketi se manter, já até removeram eles da documentação... uma pena

**Comment by on-future** [comment]
😢

**Comment by rennokki** [comment]
Soketi on Cloudflare Workers was a good test for infrastructure at Edge. It was enough to run for most people who got small loads — testing locally, small internal projects, or up to a few tens of concurrent connections. I've seen some people even reached hundreds and thousands of concurrent connections thanks to the Hibernation API, which allowed up to 32,000 connections at once.

I've decided to put the Cloudflare Workers version on pause for now, and focus on the main stage — [going Interstellar](https://interstellar.soketi.app).

If you still consider the Cloudflare Workers version to be useful for your use case, please contact me (<alex@thecodefather.co>) and explain further the use case and I will consider looking forward to it.
