### ISSUE TITLE
Multitenancy -> Laravel + Soketi broadcasting events from artisan command sending responses to default app key each time

### ISSUE THREAD

**Issue by razvan-p** [soketi/pws#1224]
Hi. I have a multitenancy app.
Followed the docs for installing Soketi with Laravel and all works well when broadcasting events from controllers.
When broadcasting events from artisan command I encounter a strange behaviour.

I have 2 apps in the config file:

```
{
    "debug": true,
    "port": 6001,
    "appManager.array.apps": [
        {
            "id": "app-id",
            "key": "app-key",
            "secret": "app-secret",
            "enabled": true,
            "enableClientMessages": true,
        },
        {
            "id": "app-id-2",
            "key": "app-key-2",
            "secret": "app-secret-2",
            "enabled": true,
            "enableClientMessages": true,
            "webhooks": []
        }
    ]
}
```

The multitenancy library switches each time the backend soketi config accordingly to the tenant app.
If I'm boardcasting an event from artisan command with `MyEvent::dispatch($data);` for tenant represented by `app-key-2` let's say, in debug mode the event appears on console like this:

```
   [Fri Aug 02 2024 11:49:41 GMT+0000 (Coordinated Universal Time)] ⚡ HTTP Payload received   
{
  name: 'App\\Events\\ScalenoteProcessedEvent',
  data: '{"data": ...}',
  channels: [ 'private-scalenotes-channel', 'private-notifications-channel' ]
}
```
From console I can see that the event is received by soketi server. But the strangeness stands in the response: instead of receiving the event for `app-key-2` app, I'm receiving it for the default one which is `app-key-1`. Maybe something is wrong with my configuration files or maybe something else? Thanks!

**Comment by eelco2k** [comment]
how are you using the app arrays in broadcasting.php ? have to specified pusher credentials in .env file? if so because config gets cached. it uses the .env 

try this with `php artisan tinker` to test if it has to do with your config being cached / already in the Config Service Container.

```php

use Pusher\Pusher; 

Artisan::call('config:clear');

Config::set('broadcasting.connections.pusher.app_id', 'SET_YOUR_APP_ID_STATICALLY');
Config::set('broadcasting.connections.pusher.key', 'SET_YOUR_KEY_STATICALLY');
Config::set('broadcasting.connections.pusher.secret', 'SET_YOUR_SECRET_STATICALLY');

// Manually reinitialize Pusher connection
$pusherConfig = Config::get('broadcasting.connections.pusher');
$pusher = new Pusher(
        $pusherConfig['key'],
        $pusherConfig['secret'],
        $pusherConfig['app_id'],
        $pusherConfig['options'] ?? []
);

// Set the Pusher instance in the broadcasting manager
Broadcast::driver('pusher')->setPusher($pusher);

// set correct namespace to your MyEvent::

App\Events\MyEvent::dispatch($data);
```
if then the event gets received in soketi with correct app-key then you know where to look. And not a soketi issue.

**Comment by razvan-p** [comment]
> how are you using the app arrays in broadcasting.php ? have to specified pusher credentials in .env file? if so because config gets cached. it uses the .env
> 
> try this with `php artisan tinker` to test if it has to do with your config being cached / already in the Config Service Container.
> 
> ```
> use Pusher\Pusher; 
> 
> Artisan::call('config:clear');
> 
> Config::set('broadcasting.connections.pusher.app_id', 'SET_YOUR_APP_ID_STATICALLY');
> Config::set('broadcasting.connections.pusher.key', 'SET_YOUR_KEY_STATICALLY');
> Config::set('broadcasting.connections.pusher.secret', 'SET_YOUR_SECRET_STATICALLY');
> 
> // Manually reinitialize Pusher connection
> $pusherConfig = Config::get('broadcasting.connections.pusher');
> $pusher = new Pusher(
>         $pusherConfig['key'],
>         $pusherConfig['secret'],
>         $pusherConfig['app_id'],
>         $pusherConfig['options'] ?? []
> );
> 
> // Set the Pusher instance in the broadcasting manager
> Broadcast::driver('pusher')->setPusher($pusher);
> 
> // set correct namespace to your MyEvent::
> 
> App\Events\MyEvent::dispatch($data);
> ```
> 
> if then the event gets received in soketi with correct app-key then you know where to look. And not a soketi issue.

OMG! Only the configs were changed together with the tenant. The new pusher initialization set up was missing:

```
Broadcast::driver('pusher')->setPusher($pusher);
```

Thank you!
