### ISSUE TITLE
[upgrade] Unable to install on Node.js 16

### ISSUE THREAD

**Issue by jskorlol** [soketi/pws#27]
Hello, I installed this with the new pws! thank you.

However, there is a problem that it cannot be installed on node 16.
[https://github.com/msgpack/msgpack-node/issues/55](https://github.com/msgpack/msgpack-node/issues/55)
So I downgraded to node 14, but can I use 16 later?

**Comment by rennokki** [comment]
Not for now. I have tried to set up Node 16 in the past but I have reverted the commits back then. This issue has to be put on hold until I get some time to seek a fix. 😁

Node 14 is LTS, so it's good to go for now. Node 16 will be supported soon.

**Comment by rennokki** [comment]
I've created the PR and I'm patiently waiting for a magical fix to happen to update the PR and solve this Node.js 16 issue 😁

**Comment by rennokki** [comment]
Did some research. Opted-in for Avro schema (works almost the same as Protobuf) to better serialize/deserialize stuff, way faster than JSON does, and dropped msgpack as it seems to be unmaintained for quite a while.

**Comment by rennokki** [comment]
So I have put in place a JSON encode/stringify method as there is already this kind of method for node-to-node communication. Byebye msgpack, Node.js 16 will be available. 😁
