### ISSUE TITLE
Docker images not working (incompatible node.js version)

### ISSUE THREAD

**Issue by Namoshek** [soketi/pws#7]
I tried to run two versions of the docker image, `soketi/pws:0.1.0-14-alpine` and `soketi/pws:latest-14-alpine`, both did produce the following error with the default environment and `DEBUG=true`:

> Error: This version of µWS is not compatible with your Node.js build:
>
> Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/uWebSockets.js/uws_linux_x64_83.node)
>     at /app/node_modules/uWebSockets.js/uws.js:22:9
>     at Object.<anonymous> (/app/node_modules/uWebSockets.js/uws.js:24:3)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:92:18)
>     at Object.<anonymous> (/app/dist/server.js:14:13)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
> /app/node_modules/uWebSockets.js/uws.js:22
>                throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());

---

I also could not find a node.js 16 image which is advertised on the Docker Hub page:

> The following versions are available:
> - `[git_version]-16-alpine`
> - `[git_version]-14-alpine`

So I went ahead and tried building with the following images:
- `16-alpine`
- `16-alpine3.11`
- `16-alpine3.12`
- `16-buster` (failed because of `apk` which is to be expected)

All unfortunately without luck. Also installing the apk package `libc6-compat` which contains `ld-linux-x86-64.so.2` didn't help.

**Comment by rennokki** [comment]
Thanks for the bug report. It seems like [alpine does not allow the core server to run](https://github.com/uNetworking/uWebSockets.js/discussions/158) due to some missing libraries. Gonna fix it asap. 🙌

**Comment by rennokki** [comment]
@Namoshek `0.1.1` should fix the issues. I have also added tests for the built images, so that any issue regarding the building won't happen again. 😁

**Comment by Namoshek** [comment]
@rennokki Thank you for the quick fix, happy to report it works great now. Literally a drop-in replacement for our current setup with `beyondcode/laravel-websockets`.

I'll now see what can be done about Redis Sentinel support. I think it is really straight forward, thanks to the implementation of `ioredis`.

**Comment by rennokki** [comment]
[Stringified JSONs are being supported](https://github.com/soketi/pws/blob/0.1.2/src/cli/cli.ts#L88-L98) when passing strings that don't fail to be parsed with `JSON.parse`, so I guess the [sentinels' configuration](https://github.com/luin/ioredis#sentinel) can be easily adopted
