### ISSUE TITLE
.env PUSHER_APP_ID not being picked up by Soketi

### ISSUE THREAD

**Issue by jonhassall** [soketi/pws#965]
**Description**
Soketi is not using the variables in my .env file for PUSHER_APP_ID

It is using the SOKETI_DEBUG variable.

**Reproduction steps**

- I Installed Soketi globally
- I created an empty directory
- I created my .env file with:
```
SOKETI_DEBUG=1
PUSHER_APP_ID=myapp-id
PUSHER_APP_CLUSTER=pusher1
PUSHER_APP_KEY=myapp-key
PUSHER_APP_SECRET=myapp-secret
```
- I started Soketi with `soketi start`
- I can see debug mode is picked up
- I connect to the web sockets server through JavaScript and I see a 4001 error in Chrome network console `"App key myapp-id does not exist."`
- If I change my JavaScript to use the default Soketi APP_ID of app-id it works, so I believe the PUSHER_APP_ID is not being picked up by Soketi.

Debug error message:
```
{
  ws: uWS.WebSocket {
    ip: '127.0.0.1',
    ip2: '',
    appKey: 'myapp-id',
    sendJson: [Function (anonymous)],
    id: '5839986082.4436051051',
    subscribedChannels: Set(0) {},
    presence: Map(0) {},
    timeout: Timeout {
      _idleTimeout: 120000,
      _idlePrev: [TimersList],
      _idleNext: [TimersList],
      _idleStart: 42252,
      _onTimeout: [Function (anonymous)],
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: false,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 131,
      [Symbol(triggerId)]: 0
    }
  },
  code: 4001,
  message: ArrayBuffer { [Uint8Contents]: <>, byteLength: 0 }
}
```

**Environment**
- Soketi version: @soketi/soketi@1.6.0
- Adapter (local, redis): local
- App Manager (array, mysql, postgres, dynamodb) : array
- Queue (sqs, redis, sync): sync
- Cache Managers (memory, redis): memory

**Configuration**
Run the server with `SOKETI_DEBUG=1` and paste the nested object configuration that outputs:
```js
{
  isMaster: true,
  isMasterEligible: true,
  weight: -0.1694800879524,
  address: '127.0.0.1',
  advertisement: undefined
}
```

**Comment by J-Brk** [comment]
Shouldn't the variable be `SOKETI_DEFAULT_APP_ID`  ?
https://docs.soketi.app/app-management/array-driver

**Comment by jonhassall** [comment]
Thanks, that did it.

**Comment by renchris** [comment]
Hi @jonhassall. I am also encountering the same error at runtime of `App key does not exist`. Additionally, for me, it does not work with the default value of `app-id` either.

<img width="792" alt="image" src="https://github.com/soketi/soketi/assets/57972348/0bf64f62-864d-4d28-bec6-2005f0125afb">

Would you mind sharing your soketi start command, soketi config file, and params for your Pusher instance?

I tried both having the env variables inline in the terminal command with `SOKETI_DEBUG=1 SOKETI_DEFAULT_APP_ID=app-id soketi start
` as well as with a config file with `soketi start --config=soketi.config.json
` and the config file of

```
{
    "debug": true,
    "port": 6001,
    "appManager.array.apps": [
      {
        "id": "app-id",
        "key": "app-key",
        "secret": "app-secret",
        "maxConnections": -1,
        "enableClientMessages": false,
        "enabled": true,
        "maxBackendEventsPerSecond": -1,
        "maxClientEventsPerSecond": -1,
        "maxReadRequestsPerSecond": -1,
        "webhooks": []
      }
    ]
  }
```

I have my `.env.local` file to be

```
NEXT_PUBLIC_SOKETI_DEFAULT_APP_ID=app-id
NEXT_PUBLIC_SOKETI_PUSHER_KEY=key
NEXT_PUBLIC_SOKETI_PUSHER_SECRET=secret
NEXT_PUBLIC_SOKETI_PUSHER_CLUSTER=us3
SOKETI_DEBUG=1
```

and trying with both initializing my Pusher instances on the client side with pusher-js and on the server side with pusher (pusher-http-node)

```
'use server'

import Pusher from 'pusher'

  const pusher = new Pusher(
    {
      appId: process.env.NEXT_PUBLIC_SOKETI_DEFAULT_APP_ID ?? 'app-id',
      key: 'key',
      secret: 'secret',
      cluster: process.env.NEXT_PUBLIC_SOKETI_PUSHER_CLUSTER ?? '',
      host: '127.0.0.1',
      port: '6001',
      useTLS: false,
    },
  )
  ```

```
'use client'

import Pusher from 'pusher-js'

    const pusher = new Pusher(process.env.NEXT_PUBLIC_SOKETI_DEFAULT_APP_ID ?? 'app-id', {
      cluster: 'us3',
      wsHost: '127.0.0.1',
      wsPort: 6001,
      forceTLS: false,
    })
```

**Comment by jonhassall** [comment]
@renchris I was using Laravel. My soketi start command was simply `soketi start`

My issue was I was assuming PUSHER_APP_ID, PUSHER_APP_KEY, and PUSHER_APP_SECRET would be picked up by soketi, but I was mistaken. It worked when I set SOKETI_DEFAULT_APP_ID, SOKETI_DEFAULT_APP_KEY and SOKETI_DEFAULT_APP_SECRET.

I didn't have to use any separate Node scripts
