### ISSUE TITLE
[BUG] Issue with send to user

### ISSUE THREAD

**Issue by CapitaineCaverne** [soketi/pws#980]
I tried with cluster pusher and my code work.
But when I switch to my soketi server, the message aren't received to browser.

I see the debug message when I push it from back.
{
  name: 'user-message',
  data: '{"payload":"..."}',
  channel: '#server-to-user-XXXX'
}

I run the serveur with basic configuration :

SOKETI_DEBUG=1 npx soketi start

I tried with docker image too.

For now it's the 1.6.0 version, I tried with 1.5.0 too.

**Comment by dpi** [comment]
make sure you've turned on user auth, `SOKETI_DEFAULT_APP_USER_AUTHENTICATION` env var is one method of doing so.

I can confirm at least `quay.io/soketi/soketi:1.6-16-debian` works just fine

**Comment by CapitaineCaverne** [comment]
Yes ! working now ! I think the documentation need to be clarify for this point.
Thank you.
