### ISSUE TITLE
https://dash.soketi.app/ seems to be down.

### ISSUE THREAD

**Issue by Wernke96** [soketi/pws#998]
https://dash.soketi.app/register seems to be down

**Comment by vivekkotadiya** [comment]
How I can get the app id and secret key for Soketi? How I can purchase plan and generate app id and secret key for soketi?

**Comment by Wernke96** [comment]
The page is up and running again so I'm closing this issue

**Comment by leoboom-isme** [comment]
https://dash.soketi.app/register is down again

**Comment by vesper8** [comment]
@Wernke96 it appears that it is down again and has been for what seems like weeks. Any ideas what's wrong? And out of curiosity, to anyone that was already set up, would this downtime have affected the usability of Soketi or is the dash just used for the initial setup? Thanks

**Comment by vivekkotadiya** [comment]
@vesper8 I don't think it will affect your app if https://dash.soketi.app/ is down. Because Soketi integration will host on your server so if your server is down only in that case your app will affect.
